### PR TITLE
Add formatting on input

### PR DESCRIPTION
**Pull request by sandi-racy**
Hi @kevinongko!

I created a feature that allows users to perform formatting during input

### CODE REVIEW

**Comment by kevinongko** [comment]
Hi @sandi-racy ,

I tried your code and I cannot input decimals properly, 
```vue
    <vue-numeric 
       currency="$"
       :format-input="true"
       v-model="money"
       separator=","
       precision="2"
     >
     </vue-numeric>
```

I also tried this approach before, formatting on input will affect decimals in a weird way https://github.com/kevinongko/vue-numeric/issues/8#issuecomment-302705933.

**Comment by sandi-racy** [comment]
I have fixed the bug, check it out

**Comment by kevinongko** [comment]
I tried your new revision using the sample code below:

```vue
<template>
  <div id="app">
    <vue-numeric
       currency="$"
       :format-input="true"
       v-model="money"
       separator=","
       precision="2"
     >
     </vue-numeric>
  </div>
</template>

<script>
import VueNumeric from 'vue-numeric'

export default {
  name: 'app',

  components: {
    VueNumeric
  },

  data () {
    return {
      money: 0
    }
  }
}
</script>
```

Whenever I try to input anything it show `NaN, undefined`
error

Can you make a live demo or repo so I can try your code in your setup? Thanks.

**Comment by sandi-racy** [comment]
Oops sorry, I never tested it using currency
Now the bug should be gone

**Comment by kevinongko** [comment]
The component cannot accept default value from v-model, it keep showing `0` it should be `1000`.
Btw your revision also break the tests.

```vue
<template>
  <div id="app">
    <vue-numeric
       currency="$"
       :format-input="true"
       v-model="money"
       separator="."
       precision="2"
     >
     </vue-numeric>
  </div>
</template>

<script>
import VueNumeric from 'vue-numeric'

export default {
  name: 'app',

  components: {
    VueNumeric
  },

  data () {
    return {
      money: 1000
    }
  }
}
</script>
```

**Comment by kevinongko** [comment]
I found another bug, when I accidentally press non numeric button on my keyboard such as alphabet  the input show `NaN, undefined`

**Comment by sandi-racy** [comment]
I have fixed the bugs, check it out and let me know if you find any bugs

**Comment by kevinongko** [comment]
I found another one, try ctrl+A to select whole input and press backspace/delete
it turn the input into `NaN, undefined`

**Comment by kevinongko** [comment]
I just add [contribution guidelines](https://github.com/kevinongko/vue-numeric/blob/master/CONTRIBUTING.md) make sure to check it out :)

**Comment by sandi-racy** [comment]
I have fixed the bug and have added some tests

**Comment by kevinongko** [comment]
Nice @sandi-racy , it's good to merge now.

one last thing, IMO the props `format-input` could be misleading.
how about `format-on-input` or `instant-format`, what do you think?

**Comment by kevinongko** [comment]
Closing due to inactivity.

**Pull request closed without merging**
